# to apply:
# kubectl apply -n dsc-10-llm -f dev.yml
#
# for password:
# kubectl get secret postgres.dsc10-tutor-logs-dev.credentials.postgresql.acid.zalan.do -o 'jsonpath={.data.password}' | base64 -d
#
# to check psql:
# kubectl run -i --tty --rm debug --image=postgres -- bash
# psql -h dsc10-tutor-logs-dev -U postgres
apiVersion: 'acid.zalan.do/v1'
kind: 'postgresql'
metadata:
  name: 'dsc10-tutor-logs-dev'
spec:
  teamId: 'dsc10'
  volume:
    size: 2Gi
    storageClass: linstor-igrok
  numberOfInstances: 1
  users:
    dsc10_tutor:
      - superuser
      - createdb
  databases:
    dsc10_tutor_logs: dsc10_tutor
  postgresql:
    version: '14'
  enableConnectionPooler: true
  resources:
    requests:
      cpu: '1'
      memory: '4Gi'
    limits:
      cpu: '2'
      memory: '8Gi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsc10-tutor-logging-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsc10-tutor-logging-api-dev
  template:
    metadata:
      labels:
        app: dsc10-tutor-logging-api-dev
    spec:
      containers:
        - name: api
          image: gitlab-registry.nrp-nautilus.io/samlau95/dsc10-tutor-logger/api:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '1'
              memory: '2Gi'
          env:
            - name: DB_HOST
              value: dsc10-tutor-logs-dev-pooler
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: dsc10_tutor_logs
            - name: DB_USER
              value: dsc10_tutor
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsc10-tutor.dsc10-tutor-logs-dev.credentials.postgresql.acid.zalan.do
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dsc10-tutor-logging-api-dev
spec:
  selector:
    app: dsc10-tutor-logging-api-dev
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsc10-tutor-logging-api-dev
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: dsc10-tutor-logging-api-dev.nrp-nautilus.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsc10-tutor-logging-api-dev
                port:
                  number: 80
  tls:
    - hosts:
        - dsc10-tutor-logging-api-dev.nrp-nautilus.io
