apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "dsc10-tutor-logs-prod"
spec:
  teamId: "dsc10"
  volume:
    size: 20Gi
    storageClass: linstor-igrok
  numberOfInstances: 2
  users:
    dsc10_tutor:
      - superuser
      - createdb
  databases:
    dsc10_tutor_logs: dsc10_tutor
  postgresql:
    version: "14"
  enableConnectionPooler: true
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsc10-tutor-logging-api-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsc10-tutor-logging-api-prod
  template:
    metadata:
      labels:
        app: dsc10-tutor-logging-api-prod
    spec:
      containers:
        - name: api
          image: ghcr.io/ucsd-dsc10/dsc10-tutor-logging-api:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: DB_HOST
              value: dsc10-tutor-logs-prod-pooler
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: dsc10_tutor_logs
            - name: DB_USER
              value: dsc10_tutor
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsc10-tutor.dsc10-tutor-logs-prod.credentials.postgresql.acid.zalan.do
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dsc10-tutor-logging-api-prod
spec:
  selector:
    app: dsc10-tutor-logging-api-prod
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsc10-tutor-logging-api-prod
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: dsc10-tutor-logging-api.nrp-nautilus.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsc10-tutor-logging-api-prod
                port:
                  number: 80
  tls:
    - hosts:
        - dsc10-tutor-logging-api.nrp-nautilus.io
